name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp-version: [26.2.5, 27.2]
        elixir-version: [1.17, 1.18]

    services:
      db:
        env:
          POSTGRES_DB: telemetry_ui_test
          POSTGRES_PASSWORD: pass1234
        image: postgres:16
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports: ["5432:5432"]

    env:
      DATABASE_POOL_SIZE: 30
      DATABASE_URL: postgres://postgres:pass1234@localhost/telemetry_ui_test
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - uses: actions/setup-node@v1
        with:
          node-version: 20.16.0

      - uses: actions/cache@v4
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ hashFiles(format('{0}/mix.lock', github.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - uses: actions/cache@v4
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles(format('{0}/mix.lock', github.workspace)) }}

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}/assets/package-lock.json', github.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: make prepare
      - run: make lint
      - run: make check-github
