name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.MIREGO_HEXPM_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.x
          elixir-version: 1.17.x

      - uses: actions/setup-node@v1
        with:
          node-version: 16.13

      - run: make prepare
      - run: mix compile --docs
      - run: mix hex.publish --yes
